# .coveralls.yml

# Your CI service name (e.g. travis-pro, circleci, etc.)
# service_name: 

# Build or Job ID (e.g. $CIRCLE_BUILD_NUM, $TRAVIS_JOB_ID, etc.). 
# `service_jobs_id` is the more modern option for identifying a build or job. 
# service_job_id: 

# URL to build details. (e.g. $CIRCLE_BUILD_URL, $TRAVIS_BUILD_WEB_URL, etc.)
# No longer required, but available for backwards compatibility.
# service_build_url: 

# The branch of the current commit. (e.g. $CIRCLE_BRANCH, $TRAVIS_BRANCH, etc.)
# service_branch: 

# The pull request number (e.g. $CIRCLE_PR_NUMBER, $TRAVIS_PULL_REQUEST, etc.)
# Only required for pull requests.
# service_pull_request: 

# We recommend only storing repo tokens for public repos in your .coveralls.yml file. 
# For private repos, we recommend storing them in your CI service's protected environment variables (aka. secrets).
repo_token: VQi6W0JTvJLHrQD20WXvFaztCf5eLljGU
